import 'package:test/test.dart';
import 'package:ciel_api/ciel_api.dart';

// tests for LoginStartRequest
void main() {
  final instance = LoginStartRequestBuilder();
  // TODO add properties to the builder and call build()

  group(LoginStartRequest, () {
    // String username
    test('to test the property `username`', () async {
      // TODO
    });

    // Random nonce generated by the client.
    // String clientNonce
    test('to test the property `clientNonce`', () async {
      // TODO
    });
  });
}
