import 'package:test/test.dart';
import 'package:ciel_api/ciel_api.dart';

// tests for StepupStartRequest
void main() {
  final instance = StepupStartRequestBuilder();
  // TODO add properties to the builder and call build()

  group(StepupStartRequest, () {
    // Random nonce generated by the client.
    // String clientNonce
    test('to test the property `clientNonce`', () async {
      // TODO
    });
  });
}
