//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'login_start_request.g.dart';

/// LoginStartRequest
///
/// Properties:
/// * [username]
/// * [clientNonce] - Random nonce generated by the client.
@BuiltValue()
abstract class LoginStartRequest
    implements Built<LoginStartRequest, LoginStartRequestBuilder> {
  @BuiltValueField(wireName: r'username')
  String get username;

  /// Random nonce generated by the client.
  @BuiltValueField(wireName: r'clientNonce')
  String get clientNonce;

  LoginStartRequest._();

  factory LoginStartRequest([void updates(LoginStartRequestBuilder b)]) =
      _$LoginStartRequest;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(LoginStartRequestBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<LoginStartRequest> get serializer =>
      _$LoginStartRequestSerializer();
}

class _$LoginStartRequestSerializer
    implements PrimitiveSerializer<LoginStartRequest> {
  @override
  final Iterable<Type> types = const [LoginStartRequest, _$LoginStartRequest];

  @override
  final String wireName = r'LoginStartRequest';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    LoginStartRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'username';
    yield serializers.serialize(
      object.username,
      specifiedType: const FullType(String),
    );
    yield r'clientNonce';
    yield serializers.serialize(
      object.clientNonce,
      specifiedType: const FullType(String),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    LoginStartRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object,
            specifiedType: specifiedType)
        .toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required LoginStartRequestBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'username':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.username = valueDes;
          break;
        case r'clientNonce':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.clientNonce = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  LoginStartRequest deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = LoginStartRequestBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}
