//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'stepup_start_request.g.dart';

/// StepupStartRequest
///
/// Properties:
/// * [clientNonce] - Random nonce generated by the client.
@BuiltValue()
abstract class StepupStartRequest
    implements Built<StepupStartRequest, StepupStartRequestBuilder> {
  /// Random nonce generated by the client.
  @BuiltValueField(wireName: r'clientNonce')
  String get clientNonce;

  StepupStartRequest._();

  factory StepupStartRequest([void updates(StepupStartRequestBuilder b)]) =
      _$StepupStartRequest;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(StepupStartRequestBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<StepupStartRequest> get serializer =>
      _$StepupStartRequestSerializer();
}

class _$StepupStartRequestSerializer
    implements PrimitiveSerializer<StepupStartRequest> {
  @override
  final Iterable<Type> types = const [StepupStartRequest, _$StepupStartRequest];

  @override
  final String wireName = r'StepupStartRequest';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    StepupStartRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'clientNonce';
    yield serializers.serialize(
      object.clientNonce,
      specifiedType: const FullType(String),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    StepupStartRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object,
            specifiedType: specifiedType)
        .toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required StepupStartRequestBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'clientNonce':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.clientNonce = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  StepupStartRequest deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = StepupStartRequestBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}
